# Introduction to our Submission System

In this exercise you will:

- Learn how to work with IPython notebooks
- Get a small numpy introduction
- Learn about our submission system

Run cells with `Shift + Enter`

## 1. IPython Notebooks
An IPython notebook is made up of a number of cells. Each cell can contain Python code. You can execute a cell by clicking on it and pressing `Shift-Enter`. When you do so, the code in the cell will be executed, and the output of the cell will be displayed beneath the cell. For example, after running the first cell the notebook looks like this:

In [ ]:
x = 5
print(x+3)

Global variables are shared between cells. Therefore, we can access `x` in the next cell.

In [ ]:
print(x+10)

By convention, IPython notebooks are expected to be run from top to bottom. Failing to execute some cells or executing cells out of order can result in errors:

In [ ]:
# This does not work
print(x+y)

In [ ]:
# After executing this cell, you can re-evaluate the cell above
y = 3

You can edit cells by double clicking them (the color on the left changes from blue to green) and change the text (not really useful) or code (will be useful).

In [ ]:
print('I have not changed the cell')

Please make sure that you are using the correct python environment. You can print out the environment path with the following cell. If you use python2 to work on the exercises and submit your model, you will encounter errors.

In [ ]:
import sys
print(sys.version)
if sys.version_info <= (3, 7):
    print("you are using an older version of python. We expect python 3.7.x \nYou can continue with your version but it might cause some issues")

After you have modified an IPython notebook for one of the assignments by modifying or executing some of its cells, remember to __save your changes__!


## 2. Imports

We start every notebook with a cell containg the important imports. So the first cell of every notebook is the import cell, as this needs to be executed before running any code.


In [ ]:
import time
import os
import random
import math
import numpy as np
import matplotlib.pyplot as plt
import numpy as np
from PIL import Image
%matplotlib inline
plt.rcParams['figure.figsize'] = (7.0, 5.0) # set default size of plots
plt.rcParams['image.interpolation'] = 'nearest'
plt.rcParams['image.cmap'] = 'gray'

# for auto-reloading extenrnal modules
# see http://stackoverflow.com/questions/1907993/autoreload-of-modules-in-ipython
%load_ext autoreload
%autoreload 2

# 3. Numpy Introduction

Numpy is a high performance framework for operations on multi dimensional arrays. It would be a nice tool in your kitty for working on later exercises and your life as a Data Scientist in general. 

In [ ]:
# Create a simple (2, 3) numpy array
# [[ 1  2  3]
#  [ 4  5  6]]
a = np.array([[1,2,3], [4,5,6]])

# Print the data type of this array
print(a.dtype)

# print the shape of this array
print(a.shape)

In [ ]:
# Slicing operation 
# Let us take the first two columns from the original array and save it in a new one
b = a[:, :2]
print(b)
print(b.shape)

In [ ]:
# Select elements which satisfy a condition
# Using numpy array makes such a selection trivial
mask = a > 1
new_array = a[mask]
new_array

In [ ]:
# Do the same thing in a single step
c = a[a>1]
assert np.all(new_array == c) #  np.all() to indicate that all the values need to match

In [ ]:
# Mathematical operations
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

In [ ]:
# Element wise operations
# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

# Element wise exponential operation
#[[ 2.71828183  7.3890561 ]
#  [20.08553692 54.59815003]] 
print(np.exp(x))

A detailed summary of numpy is beyond the scope of this assignment. Please take a look at http://docs.scipy.org/doc/numpy/reference/ for further reference. For this exercise, the tasks we have covered should be enough.

## 4. Displaying an Image #
One of the convenient things about jupyter notebooks is the ability to display images. You will not have any new clanky windows opening up and everything shall be inline. Let us take a look at a simple example here.

In [ ]:
import os
print(os.getcwd())

In [ ]:
# Load the image first
image = Image.open('images/sample_image.jpg')
plt.imshow(image)

<div class="alert alert-info">
    <h3>Inline Question</h3>
    <p>Sometimes we ask inline questions. They should help you to think about the subject that are relevant for the exam.</p>
    <p>**Your answer:** You can write your answer here to save it in the ipython notebook so you can review it before the exam. Double click a cell to edit it and enter your answer.</p>
</div>

## 5. External Files
Most of your work will involve implementing certain functions in external python files. These are contained in the `exercise_code` folder. Check out the `Dummy` class in `exercise_code/networks/dummy.py`.

In [ ]:
from exercise_code.networks.dummy import Dummy
# Instantiate a model
model = Dummy()

## 6. Dummy Machine

Usually, we ask you to train and submit models. You don't need to train anything fancy in this exercise, this is just a sample code to familarize you with file structure of our codebase.

You need to make some changes to the `forward()` method in `exercise_01/exercise_code/networks/dummy.py`and set `x` to any integer that is larger than 59. We highlight all locations where you should modify the code with boxes.

To edit these files you can use any IDE or text editor but __make sure that you don't rename or remove classes or functions__.

In this submission you get a score depending upon the number of test cases you pass. Usually, the total points you can secure is between __0 - 100__. For this exercise, you have __one test cases__ which depends on the output of the `forward()` function. You can check the `exercise_01/exercise_code/tests` folder to have a general feel about the unit tests. Please remember that these test cases are just a sample and the submission server has a set of different test cases. 

In [ ]:
from exercise_code.tests.dummy_tests import DummyTest

test_cases = DummyTest(model)
test_cases()

## 7. Model Saving
Now you need to save the model. We provide you with all the functionality, so you will only need to execute the next cell.

In [ ]:
model.save_model()

<div class="alert alert-danger">
    <h3>Warning</h3>
    <p>You might get an error like this:</p>
    <p>PicklingError: Can't pickle `<class 'exercise_code.test_model.TestModel'>`: it's not the same object as exercise_code.test_class.TestSubmission</p>
    <p>The reason is that we are using autoreload and working on this class during the notebook session. If you get this error simply restart the kernel and rerun the whole script (Kernel -> Restart & Run All) or only the important cells for generating your model.</p>
</div>

## 8. Zip File Creation
Run the following cell to create the zip file for submission, which contains all the exercise code, models, and ipynb notebooks.

In [ ]:
from exercise_code.submit import submit_exercise

submit_exercise('exercise1')

# Google Colab

We have also uploaded a notebook which introduces you to basic commands of Google Colab. Although you would not need it for this exercise but it will come in handy for the future exercises. If you are interested, you can check `2_colab_introduction.ipynb` notebook.

## References
Congratulations!! You have finished the introductory notebook.
Some references to learn how to use basic python libraries (Numpy, Scipy and Matplotlib) that you would need for this course:

[1] https://docs.python.org/3/tutorial/

[2] http://cs231n.github.io/python-numpy-tutorial/